Add podcastByGuid
SarvagyaVaish/python-podcastindex pull request #10
Opened 2024-09-24 12:38 UTC by iwootten

Adds podcast lookup through using it's guid.

2024-09-24 18:51 UTC, SarvagyaVaish requested changes
Thanks so much for contributing to the repo! Great addition :) Requesting one small change for clarity. Will approve, merge, and release a new version in PyPi after that.

2024-09-24 18:51 UTC, SarvagyaVaish commented on tests/test_podcast_lookup.py
> +guid = "f1ebeaa1-bc5a-534f-8528-0738ae374d55"
Could we call this `podcastGuid` perhaps?

2024-09-24 18:51 UTC, SarvagyaVaish commented on tests/test_podcast_lookup.py
> +    assert results["feed"]["title"] == podcastTitle, "Did not find the right podcast when doing lookup by guid"
Thanks for adding a test proactively :)

2024-09-24 23:53 UTC, SarvagyaVaish commented on tests/test_podcast_lookup.py
> +guid = "f1ebeaa1-bc5a-534f-8528-0738ae374d55"
Ahh nvm. This is already in the podcast specific test file.

2024-09-24 23:54 UTC, merged

2024-09-24 23:58 UTC, SarvagyaVaish commented
Thank you so much for your contribution. A new version with your contribution is up! 
https://pypi.org/project/python-podcastindex/#history

2024-09-25 08:51 UTC, iwootten commented
Thanks for reviewing this so quickly!